<?php
/**
 * $block->getCoreString()  \Mirasvit\Core\Helper\Text  $_coreString
 * @var \Mirasvit\Kb\Block\Article\ListArticle $block
 */
?>
<?php
$collection = $block->getArticleCollection();
?>

<?php if ($collection->count()): ?>
    <?= $block->getToolbarHtml() ?>

    <ol class="kb-articles__list">
        <?php foreach ($collection as $article): ?>
            <li class="kb-articles__article">
                <a class="kb__title" href="<?= $article->getUrl() ?>"><?= $article->getName(); ?></a>

                <div class="kb-article__metadata kb-article__metadata-list">
                    <div class="author">
                        <?php if ($block->isShowAuthor()): ?>
                            <?= $article->getUser()->getName(); ?>
                        <?php endif; ?>
                        <?php if ($block->isShowDate()): ?>
                            <?php if ($block->isShowAuthor()): ?>
                                <?= __(' posted this at '); ?>
                            <?php endif; ?>
                            <?= $block->formatDate($article->getCreatedAt(), \IntlDateFormatter::MEDIUM); ?>
                        <?php endif; ?>
                    </div>

                    <?php if ($block->isRatingEnabled()): ?>
                        <div class="rating">
                            <i class="fa fa-thumbs-o-up"></i><?= $article->getPositiveVoteNum() ?>
                        </div>
                    <?php endif ?>
                </div>

                <p class="kb__description"><?php
                $remainder = '';
                echo $this->helper('Mirasvit\Core\Helper\Text')->truncate(strip_tags($article->getSummary()), 300, ' ...', $remainder, false);
                ?></p>
            </li>
        <?php endforeach; ?>
    </ol>
    <div class="doc-section">
        <div class="doc-section-head">
            <div>
                <span>Download</span>
            </div>
            <div>
                <span>Description</span>
            </div>
            <div>
                <span>Date Uploaded</span>
            </div>
        </div>
        <div class="doc-section-row">
            <div>
                <a href=""><i class="fa fa-file-pdf-o" aria-hidden="true"></i> sample-doc-123</a><span class="size"><small>(10 kb)</small></span>
            </div>
            <div>
                <p>The largest gymnastics facility ever fitted out by Continental.  A huge facility offering a vast range of equipment for high performanc e and training</p>
            </div>
            <div>
                <span class="date">16.08.2017</span>
            </div>
        </div>
        <div class="doc-section-row">
            <div>
                <a href=""><i class="fa fa-file-pdf-o" aria-hidden="true"></i> sample-doc-123</a><span class="size"><small>(10 kb)</small></span>
            </div>
            <div>
                <p>The largest gymnastics facility ever fitted out by Continental.  A huge facility offering a vast range of equipment for high performanc e and training</p>
            </div>
            <div>
                <span class="date">16.08.2017</span>
            </div>
        </div>
        <div class="doc-section-row">
            <div>
                <a href=""><i class="fa fa-file-pdf-o" aria-hidden="true"></i> sample-doc-123</a><span class="size"><small>(10 kb)</small></span>
            </div>
            <div>
                <p>The largest gymnastics facility ever fitted out by Continental.  A huge facility offering a vast range of equipment for high performanc e and training</p>
            </div>
            <div>
                <span class="date">16.08.2017</span>
            </div>
        </div>
        <div class="doc-section-row">
            <div>
                <a href=""><i class="fa fa-file-pdf-o" aria-hidden="true"></i> sample-doc-123</a><span class="size"><small>(10 kb)</small></span>
            </div>
            <div>
                <p>The largest gymnastics facility ever fitted out by Continental.  A huge facility offering a vast range of equipment for high performanc e and training</p>
            </div>
            <div>
                <span class="date">16.08.2017</span>
            </div>
        </div>
    </div>
    <?= $block->getToolbarHtml() ?>
<?php else: ?>
    <p><?= __('There are no articles available for this category'); ?></p>
<?php endif ?>