<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<div class="pdf pdf-wrapper">

		<div class="pdf-header">
			<div class="pdf-container">
				<img src='<?php echo $this->getViewFileUrl('images/footer-logo.png'); ?>' alt="PDF Logo" />
			</div>
		</div>
		<div class="pdf-main">
			<div class="pdf-container">
				<h1>Competition model - 101 Series</h1>
				<p class="pdf-sku">23010106SS</p>
				
				<div class="pdf-product-img">
					<img src='<?php echo $this->getViewFileUrl('images/pdf-product.jpg'); ?>' alt="Product" />
				</div>

				<div class="pdf-description">
					<h2>Details</h2>
					<p>	
					101 series competition trampoline. This trampoline has been certified for use at the very highest levels of trampolining. Manufactured from heavy duty steel tubing, epoxy powder coated. Easily folded and transported. Supplied with coverall frame pads incorporating flip-out removable sections to reduce creasing of the pads whilst the trampoline is folded, and fixed height roller-stands.
					</p>
					<p>
					The 101 series also incorporates riser / elevator springs and straps. These are designed to hold the coverall pads slightly raised above the springs ensuring the weight of the pads does not affect the performance of the springs and bed in any way. In addition, by holding the pads clear of the springs, the noise created by the trampoline gymnast is reduced as the pads and springs do not hit against each other.
					</p>
					<p>
					This trampoline is supplied with either fixed height or hydraulically assisted "Safelift" roller stands. Safelift stands are a strongly recommended optional extra for this larger size heavier trampoline as they make set-up and fold-away easier and safer.
					</p>
				</div>
				<div class="pdf-table">
					<table>
						<thead>
							<tr>
								<th>SKU</th>
								<th>Options</th>
								<th>Available Colours</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>23010106SS66</td>	
								<td>Bed: 6mm x 6mm, Stands: Fixed Height</td>	
								<td>Green</td>	
							</tr>
							<tr>
								<td>23010106SS66</td>	
								<td>Bed: 6mm x 6mm, Stands: Fixed Height</td>	
								<td>Green</td>	
							</tr>
							<tr>
								<td>23010106SS66</td>	
								<td>Bed: 6mm x 6mm, Stands: Fixed Height</td>	
								<td>Green</td>	
							</tr>
							<tr>
								<td>23010106SS66</td>	
								<td>Bed: 6mm x 6mm, Stands: Fixed Height</td>	
								<td>Green</td>	
							</tr>
							<tr>
								<td>23010106SS66</td>	
								<td>Bed: 6mm x 6mm, Stands: Fixed Height</td>	
								<td>Green</td>	
							</tr>
							<tr>
								<td>23010106SS66</td>	
								<td>Bed: 6mm x 6mm, Stands: Fixed Height</td>	
								<td>Green</td>	
							</tr>
							<tr>
								<td>23010106SS66</td>	
								<td>Bed: 6mm x 6mm, Stands: Fixed Height</td>	
								<td>Green</td>	
							</tr>
						</tbody>
					</table>
				</div>
				<div class="pdf-footer">
					<p>
						Continental Sports Limited. Hill Top Road, Paddock, Huddersfield, West Yorkshire HD1 4SD. Registered in England & Wales No: 00830200. VAT No: 516 3500 76					
					</p>
					<p>
						Telephone: 01484 542051   |   Fax: 01484 539148   |   Email: sales@contisports.co.uk 
					</p>
				</div>
			</div>
		</div>

</div>