<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/

 $_product = $block->getProduct();

?>
<div class="product-buttons">
    <a class="btn-pdf" href="/pdf/?id=<?=$_product->getId(); ?>"><span>Brochure</span></a>
    <button class="btn-spares"><span></span>Spares</button>
</div>


