<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?php echo $block->getReviewsSummaryHtml($block->getProduct(), false, true) ?>
<script>
    require(["jquery"], function ($) {
        $(document).ready(function () {

            productDisplay();
		
            setDefaultOptions();

            $( window ).resize(function() {
                productDisplay();
            });

	    function setDefaultOptions() {
	          console.log("<?php echo $block->getProduct()->getId(); ?>");
                  console.log("setting default");
		  
	          $( ".poduct-options-wrapper" ).each(function() {
		console.log("found");
//	           console.log( $(this).html() );
//		  $(this).find('option:not(:empty)').first().prop('selected',true);
	      });
	    }
	
            function productDisplay() {
                var t = $(".product.media");
                if ($(".nav-toggle").is(":visible") == false) {
                    $("<style type='text/css'> .desktopProdDiv{ height:600px;} </style>").appendTo("head");
                    t.addClass("desktopProdDiv")
                    $(".product.description").css({"margin-top": "20px"});
                } else {
                    t.removeClass("desktopProdDiv")
                }
            }
        });
    });
</script>
