<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?php echo $block->getReviewsSummaryHtml($block->getProduct(), false, true) ?>
<script>
    require(["jquery"], function ($) {
        $(document).ready(function () {

            productDisplay();

            $( window ).resize(function() {
                productDisplay();
            });

            function productDisplay() {
                var t = $(".product.media");
                if ($(".nav-toggle").is(":visible") == false) {
                    $("<style type='text/css'> .desktopProdDiv{ height:600px;} </style>").appendTo("head");
                    t.addClass("desktopProdDiv")
                    $(".product.description").css({"margin-top": "20px"});
                } else {
                    t.removeClass("desktopProdDiv")
                }
            }
        });
    });
</script>
