<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?php echo $block->getReviewsSummaryHtml($block->getProduct(), false, true)?>
<script>
require(["jquery"], function ($) {
$(document).ready(function() {
var t = $(".product.media");
t.height('600');
$(".product.description").css({"margin-top":"20px"});
});
});
</script>
