<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/

// Load contiproducts class
$contiproducts = $this->getLayout()->createBlock('\Continental\Products\Block\Details');
?>

<div class="price-table">
	<div class="thead">
		<span>Qty</span>
		<span>Discount</span>
		<span>Base Price</span>
	</div>
	<div class="tbody">
		<div class="trow">
			<span>x2</span>
			<span>-5%</span>
			<span>£3,211.95</span>
		</div>
		<div class="trow">
			<span>x2</span>
			<span>-5%</span>
			<span>£3,211.95</span>
		</div>
	</div>
	<div class="tbody extra-fields" style="display: none;">
		<div class="trow">
			<span>x2</span>
			<span>-5%</span>
			<span>£3,211.95</span>
		</div>
		<div class="trow">
			<span>x2</span>
			<span>-5%</span>
			<span>£3,211.95</span>
		</div>
	</div>
	<button class="expand-table">more <small>&#x25BC;</small></button>
</div>

<script>
	require([
    "jquery"
	], function ($){

// Need to get spConfi value
		$(document).ready(function() {
		console.log("live4eggs");
               $("select").each(function() {
		
		for (var i = 0; i < $(this).length; i++){
		var t = $(this).attr("id");
		$("#" + t + " option").each(function() {
			console.log( $(this).text() +  " " + $(this).val() );
		});
//   		   var option = $(this).options[i];
		  // now have option.text, option.value
 //		  console.log( option.txt + " " + option.value );
		 }
	       });
		var trigger = $('.expand-table');

		$(trigger).click(function() {

			$('.extra-fields').slideToggle('fast');			

			$(this).toggleClass('retract-table');

			if ($(this).hasClass('retract-table')) {
				$(trigger).html('less <small>&#x25B2;</small>')
			}
			else {
				$(trigger).html('more <small>&#x25BC;</small>')
			}			
		
		});

	});
});
</script>
