<?php
/** @var \Mirasvit\Kb\Block\Category\View $block */
// @codingStandardsIgnoreFile

$rootCategory = $block->getCategory();
$children = $this->getCategoryChildren($rootCategory);
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();

?>

<?php
echo '<img src="'.$currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'kb-images/' . $rootCategory->getImage().'" />';
?>

<h1><?=  $rootCategory->getName() ?></h1>
<?= $block->getChildHtml('kb.search.form'); ?>
<?= $block->getKbPageTitle() ?>

<?php
if ($rootCategory->getDescription()): ?>
    <div class="kb__category-description">
        <?= $rootCategory->getDescription() ?>
    </div>
<?php endif ?>
<?php
$cols = 3;
$outerCount = 1;
$count = 1;
?>
<?php if ($lastKey = $children->count()): ?>

    <div class="kb-category__grid">
        <?php foreach ($children as $key => $child): ?>

            <?php $categories = $block->getCategoryChildren($child, null, true) ?>

            <section class="kb__category">
                <div class="kb__category-title">
                    <h2><?= $child->getName() ?></h2>

                    <p><?= $child->getDescription() ?></p>
                </div>

                <?php if ($categories->count()): ?>
                    <ol>
                    <?php foreach ($categories as $category): ?>
                        <li>
                            <a href="<?= $category->getUrl() ?>">
                                <i class="fa fa-fw fa-arrow-right"></i> <?php
                                echo $category->getName() . $block->getArticleAmount($category);
                                ?>
                            </a>
                        </li>

                        <?php if ($count % $cols === 0): ?>
                            </ol>
                            <ol>
                        <?php endif; ?>
                        <?php $count++; ?>
                    <?php endforeach ?>
                    </ol>
                    <?php if ($categories->getSize() > $block->getPageLimit()): ?>
                        <div class="kb__category-view">
                            <a href="<?= $child->getUrl() ?>">
                                <?= __('View All %1 categories', $categories->getSize()) ?>
                            </a>
                        </div>
                    <?php endif ?>
                <?php else: ?>
                    <ol>
                        <?php /** @var \Mirasvit\Kb\Model\ResourceModel\Article\Collection $articles */ ?>
                        <?php $articles = $block->getArticleCollection($child) ?>
                        <?php foreach ($articles as $article): ?>
                            <li>
                                <a href="<?= $article->getUrl() ?>">
                                    <i class="fa fa-fw fa-file-text-o"></i> <?= $article->getName() ?>
                                </a>
                            </li>
                        <?php endforeach ?>
                    </ol>
                    <?php if ($articles->getSize() > $block->getPageLimit()): ?>
                        <div class="kb__category-view">
                            <a href="<?= $child->getUrl() ?>">
                                <?= __('View All %1 articles', $articles->getSize()) ?>
                            </a>
                        </div>
                    <?php endif ?>
                <?php endif ?>
                <?php if ($outerCount != $lastKey): ?>
                    <div class="section-divider">&nbsp;</div>
                <?php
                endif;
                $outerCount++;
                ?>

            </section>

        <?php endforeach ?>
    </div>
<?php else: ?>
    <?= $block->getChildBlock('kb.category.articles')->setCategory($rootCategory)->toHtml(); ?>
<?php endif ?>
    
<?php
$showTitle = true;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$documents = $objectManager->create('\Continental\Documents\Model\ResourceModel\Documents\Collection');
$documents->load();

foreach ($documents as $document) {
    $assigns = json_decode($document->getAssigns(), true);
    foreach ((array)$assigns as $assign) {
        if($block->getCategory()->getCategoryId() == intval(trim($assign, 'c'))) {
            if ( $showTitle === true): ?>
            <h2 style="margin-top: 30px;margin-bottom: 30px;"><?php echo __('Downloads') ?></h2>
            <?php endif;
            $showTitle = false;
            
            echo '<div style="float: left; width: 28%; padding-right: 10px;">';
            echo '<a href="'.$this->getUrl('pub/media').$document->getDocumentfile().'"><img style="float: left;" src="'.$this->getUrl('pub/media').'/pdf/pdf-icon.png" /> <span style="margin-left: 5px; margin-top: 5px;">'.$document->getTitle().'</span></a>';
            echo '<div style="margin-left: 25px;">'.$document->getDescription().'</div>';
            echo '</div>';
            break;
        }
    }
}
?>