<?php
$helper = $this->helper('Continental\GalleryGrid\Helper\Data');
$gridImage = $helper->getGridImages();
$count = 0;
if (!empty($gridImage)): ?>
<h3>Image Grid Title Text</h3>
    <div class="gallery_row">
    <?php foreach ($gridImage as $key => $image): ?>
    <?php if ($count%3 === 0): ?>
    </div><div class="gallery_row" style="clear:both">
        <?php endif; ?>
        <div style="float: left"><img width="200" src="<?=$image->getUrl(); ?>" />
	<p>Ipsum Lorem</p>
</div>
	
        <?php $count++; ?>
<?php endforeach; ?>
</div>
<?php endif;?>

