<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="social-icons">
	<a href="https://www.linkedin.com/company/8603594/" title="Linked In" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
	<a href="http://twitter.com/#!/contisports" title="Twitter" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
	<a href="http://www.facebook.com/pages/Continental-Sports/219102714770371" title="Facebook" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
</div>
