<form class="form " id="" action="<?php $block->getUrl('catalogsearch/result') ?>" method="get">
    <div class="block block-content search-results-box">
        <div class="field">
            <label class="label">
                <span>Search</span>
            </label>
            <div class="control" style="position: relative;">
                <div class="actions">
                    <button type="submit" title="Search" class="action">
                        <span>Search</span>
                    </button>
                </div>
                <input type="text" name="q" placeholder="Search our products" maxlength="128" autocomplete="off">
            </div>
        </div>
    </div>
</form>