<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php 
//$testClass = 'Magento_Forms_Contact_Forms_ContactForms';
//$testClass = 'Magento_Forms_Contact_Forms';
//$testClass = 'Contact_Forms/ContactForms';
$testClass = 'Continental_Forms\ContactForms';
//$testClass = 'Continental_Forms/ContactForms';
$testClass = '\Magento\Contact\Block\ContactForm';

//$contiForms = $this->getLayout()->getBlockSingleton($testClass);
$contiForms = $this->getLayout()->createBlock($testClass);
//echo $contiForms->directoryBlock->getCountryHtmlSelect();
 ?>
<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Direct Payment') ?></span></legend><br />
 <!--       <div class="field note no-label"><?php /* @escapeNotVerified */ echo __('Jot us a note and we’ll get back to you as quickly as possible.') ?></div> -->

        <div class="field name required">
            <label class="label" for="title"><span><?php /* @escapeNotVerified */ echo __('Title') ?></span></label>
            <div class="control">
                <input name="titlee" id="titlee" title="<?php /* @escapeNotVerified */ echo __('Title') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>

        </div>


        <div class="field name required">
            <label class="label" for="firstame"><span><?php /* @escapeNotVerified */ echo __('First Name') ?></span></label>
            <div class="control">
                <input name="firstname" id="firstname" title="<?php /* @escapeNotVerified */ echo __('First Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('firstname') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
</div>


        <div class="field name required">
            <label class="label" for="lastname"><span><?php /* @escapeNotVerified */ echo __('Last Name') ?></span></label>
            <div class="control">
                <input name="lastname" id="lastname" title="<?php /* @escapeNotVerified */ echo __('Last Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('lastname') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
</div>


        <div class="field name">
            <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
            <div class="control">
                <input name="company" id="company" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('company') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:false}"/>
            </div>
</div>

<!--
        <div class="field name required">
            <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
</div>
-->

        <div class="field telephone">
            <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Telephone') ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Telephone') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
            </div>
        </div>


        <div class="field email required">
            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>

        <div class="field address1 required">
            <label class="label" for="address1"><span><?php /* @escapeNotVerified */ echo __('Address#1') ?></span></label>
            <div class="control">
                <input name="address1" id="address1" title="<?php /* @escapeNotVerified */ echo __('Address#1') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('address1')) ?>" class="input-text" type="text" />
            </div>
        </div>


        <div class="field address2 required">
            <label class="label" for="address2"><span><?php /* @escapeNotVerified */ echo __('Address#2') ?></span></label>
            <div class="control">
                <input name="address1" id="address1" title="<?php /* @escapeNotVerified */ echo __('Address#2') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('address2')) ?>" class="input-text" type="text" />
            </div>
        </div>

    <div class="field postcode required">
            <label class="label" for="postcode"><span><?php /* @escapeNotVerified */ echo __('Post Code') ?></span></label>
            <div class="control">
                <input name="postcode" id="postcode" title="<?php /* @escapeNotVerified */ echo __('Post Code') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
            </div>
        </div>

    <div class="field county">
            <label class="label" for="county"><span><?php /* @escapeNotVerified */ echo __('County') ?></span></label>
            <div class="control">
                <input name="county" id="county" title="<?php /* @escapeNotVerified */ echo __('County') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('county')) ?>" class="input-text" type="text" />
            </div>
        </div>

    <div class="field country">
            <label class="label" for="country"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
            <div class="control">
                <select name="country" id="country" title="<?php /* @escapeNotVerified */ echo __('Country') ?>" class="select-text" type="text">
					<option value="">Please select</option>
				</select>
            </div>
        </div>



        <div class="field message">
            <label class="label" for="message"><span><?php /* @escapeNotVerified */ echo __('Message') ?></span></label>
            <div class="control">
                <textarea name="" id="message" title="<?php /* @escapeNotVerified */ echo __('Message') ?>" class="input-text" cols="5" rows="3" data-validate="{required:false}"><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
            </div>
        </div>


        <div class="field message">
            <label class="label" for="contact-method"><span><?php /* @escapeNotVerified */ echo __('Preferred contact method') ?></span></label>
            <div class="control">
                <select name="contact-method" id="contact-method" title="<?php /* @escapeNotVerified */ echo __('Preferred contact method') ?>" class="select-text"  data-validate="{required:true}"><option value="telephone">Telephone</option><option value="email">Email</option></select>
            </div>
        </div>

        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
