<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$om =   \Magento\Framework\App\ObjectManager::getInstance();

//$contiForms = $this->getLayout()->createBlock('\Magento\Contact\Block\ContactForm');
$contiForms = $this->getLayout()->createBlock('\Continental\Forms\Block\ContactForms');

/* Get customer details */
$formData = $contiForms->customerDetails();
?>
<?php
	$test =  '\Braintree\ClientToken';
	Braintree\Configuration::merchantId('hskdkw4bv8v49vr9');
	Braintree\Configuration::environment('sandbox');
	Braintree\Configuration::publicKey('j8w5xhzjs9bvb2rv');
	Braintree\Configuration::privateKey('ff2238a060754e6d3f4673618f110a60');

	$args = array(':customer_id' => '3023202');
	$args = array();
	// Testing

	$clientToken = $om->create($test)->generate($args);
?>
<form class="form contact direct"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="title"><span><?php /* @escapeNotVerified */ echo __('Title') ?></span></label>
            <div class="control">
                <input name="titlee" id="titlee" title="<?php /* @escapeNotVerified */ echo __('Title') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>

        </div>


        <div class="field name required">
            <label class="label" for="firstame"><span><?php /* @escapeNotVerified */ echo __('First Name') ?></span></label>
            <div class="control">
                <input name="firstname" id="firstname" title="<?php /* @escapeNotVerified */ echo __('First Name') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
</div>


        <div class="field name required">
            <label class="label" for="lastname"><span><?php /* @escapeNotVerified */ echo __('Last Name') ?></span></label>
            <div class="control">
                <input name="lastname" id="lastname" title="<?php /* @escapeNotVerified */ echo __('Last Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('lastname') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
</div>


        <div class="field name">
            <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
            <div class="control">
                <input name="company" id="company" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('company') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:false}"/>
            </div>
</div>

    <div class="field telephone">
            <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Telephone') ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Telephone') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
            </div>
        </div>


        <div class="field email required">
            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>

        <div class="field address1 required">
            <label class="label" for="address1"><span><?php /* @escapeNotVerified */ echo __('Address#1') ?></span></label>
            <div class="control">
                <input name="address1" id="address1" title="<?php /* @escapeNotVerified */ echo __('Address#1') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('address1')) ?>" class="input-text" type="text" />
            </div>
        </div>


        <div class="field address2 required">
            <label class="label" for="address2"><span><?php /* @escapeNotVerified */ echo __('Address#2') ?></span></label>
            <div class="control">
                <input name="address1" id="address1" title="<?php /* @escapeNotVerified */ echo __('Address#2') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('address2')) ?>" class="input-text" type="text" />
            </div>
        </div>

    <div class="field postcode required">
            <label class="label" for="postcode"><span><?php /* @escapeNotVerified */ echo __('Post Code') ?></span></label>
            <div class="control">
                <input name="postcode" id="postcode" title="<?php /* @escapeNotVerified */ echo __('Post Code') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
            </div>
        </div>

    <div class="field county">
            <label class="label" for="county"><span><?php /* @escapeNotVerified */ echo __('County') ?></span></label>
            <div class="control">
                <input name="county" id="county" title="<?php /* @escapeNotVerified */ echo __('County') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('county')) ?>" class="input-text" type="text" />
            </div>
        </div>

    <div class="field country">
            <label class="label" for="country"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
            <div class="control">
          	<?php echo $contiForms->getCountries(); ?>
            </div>
        </div>

        <div class="field message">
            <label class="label" for="message"><span><?php /* @escapeNotVerified */ echo __('Message') ?></span></label>
            <div class="control">
                <textarea name="" id="message" title="<?php /* @escapeNotVerified */ echo __('Message') ?>" class="input-text" cols="5" rows="3" data-validate="{required:false}"><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?>

	<?php
        $cartData = $om->create('Magento\Checkout\Model\Cart')->getQuote()->getAllItems();
        $cartDataCount = count( $cartData );

	foreach($cartData as $item) {
    echo 'ID: '.$item->getProductId().' ';
    echo 'Name: '.$item->getName().' ';
    echo 'Sku: '.$item->getSku().' ';
    echo 'Quantity: '.$item->getQty().' ';
    echo 'Price: '.$item->getPrice();
    echo PHP_EOL;
}
?>
</textarea>
            </div>
        </div>

    <div class="field reference required ">
            <label class="label" for="reference"><span><?php /* @escapeNotVerified */ echo __('Reference') ?></span></label>
            <div class="control">
                <input name="reference" id="referemce" title="<?php /* @escapeNotVerified */ echo __('Reference') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('county')) ?>" class="input-text" type="text" />
            </div>
        </div>

<div class="field amount">
            <label class="label" for="amount"><span><?php /* @escapeNotVerified */ echo __('Payment amount') ?> &pound;</span></label>
            <div class="control">
                <input name="amount" id="amount" title="<?php /* @escapeNotVerified */ echo __('Payment amount') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('amount')) ?>" class="input-text" type="text" />
            </div>
        </div>

			<div class="field contact-method">
				<label class="label" for="contact-method"><span><?php /* @escapeNotVerified */ echo __('Preferred contact method') ?></span></label>
				<div class="control">
					<select name="contact-method" id="contact-method" title="<?php /* @escapeNotVerified */ echo __('Preferred contact method') ?>" class="select-text"  data-validate="{required:true}"><option value="telephone">Telephone</option><option value="email">Email</option></select>
				</div>
			</div>

        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
<!-- Braintree form goes here>
		<fieldset>
			<div class="field card-number">
				<label class="label" for="card-number"><span><?php /* @escapeNotVerified */ echo __('Card Number') ?></span></label>
				<div class="control"> -->
<!--
				</div>
			</div>
		</fieldset>
-->
    <div id="payment-form" class="paymentWrapper" style="width:50%;max-width:630px;margin: 0 auto;">
        <label class="label">Card Number</label>
        <div id="card-number" class="hosted-field"></div>
        <label class="label label-small">CVV</label>
        <div id="cvv" class="hosted-field"></div>
        <label class="label label-small">Expiration Date</label>
        <div id="expirationDate" class="hosted-field"></div>

        <input type="text" name="email" id="email" />
        <input type="text" name="payment-method-nonce"/>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="btn btn-primary">
                    <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                </button>
            </div>
        </div>
    </div>
    
</form>
<?php 
$testcardnumber = '5555555555554444';
$testexpiration = '10 / 2019';
$testcvv 	= '123';
?>



<script>

require(["jquery", "braintreeClient", "hostedFields"], function($, client, hostedFields) {

    var authorization = "<?php echo $clientToken; ?>";

    var form = document.getElementById('payment-form');

    client.create({
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt',
	'border': '1px solid #c2c2c2',
        'height': '25px'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '<?php echo $testcardnumber; ?>'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '<?php echo $testcvv; ?>'
      },
      expirationDate: {
        selector: '#expirationDate',
        placeholder: '<?php echo $testexpiration; ?>'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    form.addEventListener('submit', function (event) {
      event.preventDefault();
	alert("send to brtree");
      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
	alert("error with token: " + tokenizeErr);
         tokenErrorHandler(tokenizeErr);
          return;
        }

        document.querySelector('input[name="payment-method-nonce"]').value = payload.nonce;
	// Populate hidden fields
	jQuery("#payment-form #email").val( jQuery("#contact-form #email").val() );
        form.submit();
      });
    }, false);
  });
});

// function to handle tokenizeerrors 
function tokenErrorHandler(tokenizeErr) {
 switch (tokenizeErr.code) {
      case 'HOSTED_FIELDS_FIELDS_EMPTY':
        // occurs when none of the fields are filled in
        console.error('All fields are empty! Please fill out the form.');
        break;
      case 'HOSTED_FIELDS_FIELDS_INVALID':
        // occurs when certain fields do not pass client side validation
        console.error('Some fields are invalid:', tokenizeErr.details.invalidFieldKeys);
        break;
      case 'HOSTED_FIELDS_TOKENIZATION_FAIL_ON_DUPLICATE':
        // occurs when:
        //   * the client token used for client authorization was generated
        //     with a customer ID and the fail on duplicate payment method
        //     option is set to true
        //   * the card being tokenized has previously been vaulted (with any customer)
        // See: https://developers.braintreepayments.com/reference/request/client-token/generate/#options.fail_on_duplicate_payment_method
        console.error('This payment method already exists in your vault.');
        break;
      case 'HOSTED_FIELDS_TOKENIZATION_CVV_VERIFICATION_FAILED':
        // occurs when:
        //   * the client token used for client authorization was generated
        //     with a customer ID and the verify card option is set to true
        //     and you have credit card verification turned on in the Braintree
        //     control panel
        //   * the cvv does not pass verfication (https://developers.braintreepayments.com/reference/general/testing/#avs-and-cvv/cid-responses)
        // See: https://developers.braintreepayments.com/reference/request/client-token/generate/#options.verify_card
        console.error('CVV did not pass verification');
        break;
      case 'HOSTED_FIELDS_FAILED_TOKENIZATION':
        // occurs for any other tokenization error on the server
        console.error('Tokenization failed server side. Is the card valid?');
        break;
      case 'HOSTED_FIELDS_TOKENIZATION_NETWORK_ERROR':
        // occurs when the Braintree gateway cannot be contacted
        console.error('Network error occurred when tokenizing.');
        break;
      default:
        console.error('Something bad happened!', tokenizeErr);
    }
//    console.log('Got nonce:', payload.nonce);
}

});

</script>
