<?php
//@codingStandardsIgnoreFile

/** @var \Mirasvit\Blog\Block\Sidebar\Recent $block */
$collection = $block->getCollection()
    ->setPageSize($this->getPageSize());
?>
<div class="block blog__sidebar-recent">
   <!--  <div class="block-title">
        <strong><?= __('Recent Posts') ?></strong>
    </div> -->
<?php 
	//Limit to 2 posts only
$i = 0; ?>
    <div class="block-content">
        <ol class="items">
            <?php foreach ($collection as $post): ?>
                <?php
                $imgPath = $post->getWidgetFeaturedImageUrl($block->getImageWidth(), $block->getImageHeight());
                ?>
                <li class="item">
                    <?php if ($imgPath): ?>
                        <a href="<?= $post->getUrl() ?>">
                            <div class="blog__post-featured-image" style="background-image: url('<?= $imgPath ?>');">
                                <div class="home-news-head">
                                    <span><?= $post->getName() ?><?= $post->getToDateFormat() ?></span>
                                    <span class="btn btn-primary"><span>Read More</span></span>
                                </div>
                            </div>                            
                         </a>

                    <?php endif ?>

                    
                </li>
            <?php 
		$i++;
		if ($i >=2) return;
		 endforeach; ?>
        </ol>
    </div>
</div>
