<div class="spares_table_wrapper">
    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
    ?>
    <table>
        <script>
            require([
                "jquery"
            ], function ($) {
                var html = '';
                <?php
                $helper = $this->helper('Continental\Spares\Helper\Listing');

                $x = $helper->filterSpares('master_product_sku', $block->getProduct()->getSku());
                $count = 0;
		if (count($x) > 0) {
                foreach ($x as $item): ?>
                    <?php $spare = $item->getData(); ?>
                    <?php
                        if ( preg_match('/\.[A-Za-z]{3}/', trim($spare['spareimage']))) {
                            echo '$(".image-map img").attr("src","' . $spare['spareimage'] . '");';
                        }
                    ?>
                        html += '<a class="map-section" style="width:<?= $helper->getLocation($spare['location'])[0] ?>px; height:<?= $helper->getDimensions($spare['dimensions'])[0] ?>px;top:<?=  $helper->getLocation($spare['location'])[0] ?>px;left:<?= $helper->getDimensions($spare['dimensions'])[0]; ?>px;" href="#"></a>';
                    <?php
                endforeach;
		}
                ?>
                $(".image-map").append(html);
            });
        </script>
    <?php
    $related = $this->getLayout()->createBlock('\Continental\Spares\Block\RelatedProducts');
    $collection = $related->getRelatedProducts();
    if ($collection): ?>
        <tr>
        <?php
        //foreach ($collection as $index => $relatedProduct):
        // testing
        $relatedProduct = $collection[0];
        for ($index = 0; $index <= 14; $index++): ?>


            <?php echo ( ( ($index % 3) == 0) && ($index > 0)) ? '</tr><tr>' : ''; ?>
            <td><img height="45" src="/pub/media/catalog/product/<?= $relatedProduct['image'] ?>" /></td>
            <td class="rowText" hover-data="{100,100,100,100}">
                <ul>
                    <li class="sparesName">
                        <?= $relatedProduct['title'] ?>
                    </li>
                    <li><?= $relatedProduct['sku'] ?></li>
                    <li class="sparesPrice">&pound;<?= $relatedProduct['price'] ?></li>
                </ul>
            </td>

            <td>
                <?php
                $addToCartUrl = $block->getAddToCartUrl($helper->getProductBySku($relatedProduct['sku']));
                ?>
                <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post">
                    <?php echo $block->getBlockHtml('formkey')?>
                    <div class="btn">
                        <button type="submit" title="Add to Cart" class="action tocart primary">
                            <span>Add to Cart</span>
                        </button>
                    </div>
                </form>
            </td>

        <?php
        endfor;
        //endforeach;
        endif;
        ?>
        </tr>
    </table>
</div>
