<div class="spares_table_wrapper">
    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
    $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
    $currentStore = $storeManager->getStore();
    ?>
<div class="image-map">
    <img src="no-image.png" alt="<?php $block->getProduct()->getName() ?>" />
</div>
    <table>
        <script>
            require([
                "jquery"
            ], function ($) {
                var html = '';
                <?php
                $helper = $this->helper('Continental\Spares\Helper\Listing');

                $x = $helper->filterSpares('master_product_sku', $block->getProduct()->getSku());
                $count = 0;
		if (count($x) > 0) {
                foreach ($x as $item):

                ?>
                    <?php $spare = $item->getData();
                    if(empty($helper->getLocation($spare['location'])[0]) || empty($helper->getDimensions($spare['dimensions'])[0])) {
                        continue;
                    }
                    ?>
                    <?php

                echo '$(".image-map img").attr("src","' . $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'spares/' . $spare['spareimage'] . '");';

                    ?>
                        html += '<a class="map-section" style="left:<?= $helper->getLocation($spare['location'])[0] ?>px; top:<?= $helper->getLocation($spare['location'])[1] ?>px;width:<?=  $helper->getDimensions($spare['dimensions'])[0] ?>px;height:<?= $helper->getDimensions($spare['dimensions'])[1]; ?>px;" href="#"><?php echo $spare['sku'] ?></a>';
                    <?php
                endforeach;
		}
                ?>
                $(".image-map").append(html);
            });
        </script>
    <?php
    $related = $this->getLayout()->createBlock('\Continental\Spares\Block\RelatedProducts');
    $collection = $related->getRelatedProducts();
    if ($collection): ?>
        <tr>
        <?php
        foreach ($collection as $index => $relatedProduct):
        ?>


            <?php echo ( ( ($index % 3) == 0) && ($index > 0)) ? '</tr><tr>' : ''; ?>
            <td><img height="45" src="/pub/media/catalog/product/<?= $relatedProduct['image'] ?>"  alt="<?php $block->getProduct()->getName() ?>" /></td>
            <td class="rowText" hover-data="{100,100,100,100}">
                <ul>
                    <li class="sparesName">
                        <?= $relatedProduct['title'] ?>
                    </li>
                    <li><?= $relatedProduct['sku'] ?></li>
                    <li class="sparesPrice">&pound;<?= $relatedProduct['price'] ?></li>
                </ul>
            </td>

            <td>
                <?php
                $addToCartUrl = $block->getAddToCartUrl($helper->getProductBySku($relatedProduct['sku']));
                ?>
                <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post">
                    <?php echo $block->getBlockHtml('formkey')?>
                    <div class="btn">
                        <button type="submit" title="Add to Cart" class="action tocart primary">
                            <span>Add to Cart</span>
                        </button>
                    </div>
                </form>
            </td>

        <?php
        endforeach;
        endif;
        ?>
        </tr>
    </table>
</div>
<style>
    .map-section {
        position: absolute;
        background-color: rgba(51, 51, 51, 0.3);
        color: white;
        text-align: center;
        padding: 3px;
    }

    .map-section:hover {
        position: absolute;
        color: white;
        text-decoration: none;
        background-color: rgba(51, 51, 51, 0.9);
    }

    .spares-top-left {
        display: none;
    }
</style>