<?php
/**
 * Features view template
 *
 * @var $block \Continental\HomeFeatures\Block\Features
 */
?>

<div class="home-feature-box">
  <div class="feature-box-top">
    <h2><?= $block->getTitle("left"); ?></h2>
    <a href="/technical-information" title="Technical Information" class="btn btn-primary"><span>Explore our resources</span></a>
  </div>
      <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-technical')->toHtml();?>
  <img src='<?php echo $this->getViewFileUrl('images/paper-box.png'); ?>' alt="my-image"/>
</div>
<div class="home-feature-box">
  <div class="feature-box-top">
    <h2><?= $block->getTitle("right"); ?></h2>
    <form>
      <input type="text" placeholder="Search our spares"/>
      <button type="submit" class="">
          <i class="fa fa-search"></i>
      </button>
    </form>
  </div>
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-spares')->toHtml();?>
    <img class="spares-box-img" src='<?php echo $this->getViewFileUrl('images/spares-box2.png'); ?>' alt="my-image"/>
</div>

