<div class="main-banner">
    <div class="banner-container">
        <div class="banner-block">
            <h2 class="bannerTitle"></h2>

            <p class="bannerText"></p>
            <a id="bannerTarget" href="" title="" class="btn btn-primary"><span>Learn More</span></a>
        </div>
    </div>
</div>
<script>
    require([
        "jquery"
    ], function ($) {
        var Banners = [];
<?php
            $bannersBlock = $this->getLayout()->createBlock('\FME\Banners\Block\Banners');
            $banners = $bannersBlock->getFrontBanners();
            $arrCount = count($banners);
            $bannerIndex = rand(1, $arrCount - 1) + 1;
            foreach ($banners as $index => $banner) {
            echo PHP_EOL;
            echo '    Banners[' . $index . '] = { ';
            echo ' image:"' . $banner->getBannerimage()  . '", title:"' . trim($banner->getTitle())  . '", ';
            echo 'text:"'. $banner->getBannertext() .'", target:"' . $banner->getTarget() .'", style:"';
            echo ($banner->getTextcolour() == 0) ? '#333333' : '';
            echo '"   }';
            }
?>
        var randomIndex = Math.floor(Math.random() * Banners.length);
        var sBanner = Banners[randomIndex];
        $(".main-banner").css("background-image", "url('/pub/media/" + sBanner.image + "')");
        $(".main-banner h2").html(sBanner.title);
        $(".main-banner .bannerText").html(sBanner.text);
        $("#bannerTarget").attr("href", sBanner.target);
        if (sBanner.style != '') {
            $(".main-banner h2").css("color", sBanner.style);
            $(".main-banner p").css("color", sBanner.style);
        }
    });
</script>
