<?php
/**
 * Features view template
 *
 * @var $block \Continental\HomeFeatures\Block\Features
 */
?>

<div class="home-feature-box">
  <div class="feature-box-top">
    <h2>Technical</h2>
    <a href="/knowledge-base" title="Knowledge Base" class="btn btn-primary"><span>Explore our resources</span></a>
  </div>
  <p>
    Lorem ipsum dolor sit amet, id utinam antiopam
    democritum his. Pro ad meliore eligendi
    moderatius. In his modo minim.
  </p>
  <img src='<?php echo $this->getViewFileUrl('images/paper-box.png'); ?>' alt="my-image"/>
</div>
<div class="home-feature-box">
  <div class="feature-box-top">
    <h2>Spares</h2>
    <form>
      <input type="text" placeholder="Search our spares"/>
      <button type="submit" class="">
          <i class="fa fa-search"></i>
      </button>
    </form>
  </div>
  <p>
    Lorem ipsum dolor sit amet, id utinam antiopam
    democritum his. Pro ad meliore eligendi
    moderatius. In his modo minim.
  </p>
  <img class="spares-box-img" src='<?php echo $this->getViewFileUrl('images/spares-box2.png'); ?>' alt="my-image"/>
</div>

