<?php
echo "Testin: " . $this->getBlockTitle();
echo ']';
?>

<div class="banner-image" style="background:url('xxxxx'); background-color:#000; width:100%;height:200px;">
	<div class="banner-container">
		<div class="banner-block">
			<h2> </h2>
			<p>Lorem ipsum dolor sit amet, id utinam antiopam democritum his.</p>
			<p>Pro ad meliore eligendi moderatius.</p>
			<p>In his modo minim.</p>
			<a href="" title="" class="btn btn-primary"><span>Learn More</span></a>
		</div>
	</div>
</div>
