<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$categories = $block->getCurrentProduct()->getCategoryIds();
$cat = $objectManager->create('Magento\Catalog\Model\Category')->load($categories[0]);

if ($parent = $cat->getParentCategory()) {
    $html = $parent->getName() . ' <b>></b> <span style="color: #d1242e;">' . $cat->getName() . '</span>';
} else {
    $html = '<div style="color: #d1242e;">' . $cat->getName() . '</div>';
}

?>
<div style="margin-top: 30px;text-transform: uppercase;">
    <?php echo $html; ?>
</div>
<div class="page-title-wrapper product">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper"
              itemprop="name"><?php echo $block->getCurrentProduct()->getName() ?></span></h1>
</div>
