<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div data-block="minicart" class="minicart-wrapper">

    <a class="action showcart fa fa-shopping-cart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
        <span class="text"><?php /* @escapeNotVerified */ echo __('My Cart'); ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
<!-- The basket is rendered here -->
<?php
    // use helper here to check if enquiry
    $enquiry = false;
    $accessories = $this->helper('Continental\Products\Helper\Accessories');
    $hidemeHelper = $this->helper('Amasty\HidePrice\Helper\Data');
    $cart = $this->helper('\Magento\Checkout\Helper\Cart');
    // Loop through
        $quote = $cart->getQuote();
        //$items = $quote->getAllItems();
        $items = $quote->getAllVisibleItems();
        //$items = $this->_cart->getEvent()->getQuote()->getAllVisibleItems(); // get only visible items
        $maxId = 0;
        foreach ($items as $item){
            // Get Product as object
            $product = $accessories->getProductByID( $item->getProductId() );
            if ( $hidemeHelper->isNeedHideProduct( $product ) ) {
                $enquiry = true;
            }
        }
?>
        <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
            <?php echo $block->getChildHtml('minicart.addons'); ?>
        </div>
    <?php endif ?>
    <script>
        require(["jquery"], function ($) {
            $(".showcart").click(function() {
    <?php if ($enquiry === false): ?>
	    // Hide if visible
                $("#top-cart-btn-checkout").show();
                $(".poa_wrapper").hide();
    <?php else: ?>
            $("#top-cart-btn-checkout").hide();
            $(".poa_wrapper").show();
                $("#top-cart-enquiry-btn").click(function() {
                   window.location = '/poa';
                });
    <?php endif; ?>
            });
        });

        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;

    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>


