<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>

<?php
            // use helper here to check if enquiry
            $enquiry = false;

            $hidemeHelper = $this->helper('Amasty\HidePrice\Helper\Data');

                if ($hidemeHelper->isNeedHideProduct($_product)) {
                    $enquiry = true;
                }

            if(!$enquiry) {

                if ($_product->getTypeId() == 'simple' || $_product->getTypeId() == 'virtual'): ?>
                    <div class="price-box price-final_price" data-role="priceBox"
                         data-product-id="<?php echo $_product->getId() ?>">
    <span class="price-container">
    <span id="product-price-<?php echo $_product->getId() ?>"
          data-price-amount="<?php echo $_product->getFinalPrice() ?>" data-price-type="finalPrice"
          class="price-wrapper " itemprop="price">
        <span class="price"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_product->getFinalPrice(),
                true, false); ?></span>
    </span>
    </span>
                    </div>
                <?php endif; ?>

                <?php $buttonTitle = __('Add to Cart'); ?>
                <?php if ($_product->isSaleable()): ?>
                    <div class="box-tocart">
                        <div class="fieldset">
                            <?php if ($block->shouldRenderQuantity()): ?>
                                <div class="field qty">
                                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                                            echo __('Qty') ?></span></label>
                                    <div class="control">
                                        <button type="button" class="subtract">-</button>
                                        <input type="number"
                                               name="qty"
                                               id="qty"
                                               maxlength="12"
                                               value="<?php /* @escapeNotVerified */
                                               echo $block->getProductDefaultQty() * 1 ?>"
                                               title="<?php /* @escapeNotVerified */
                                               echo __('Qty') ?>" class="input-text qty"
                                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                        />

                                        <button type="button" class="add">+</button>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <div class="actions">
                                <button type="submit"
                                        style="
    background-color: #d1242e;
    border: 1px solid #d1242e;
    color: #ffffff;
    text-transform: uppercase;
    padding-top: 10px;
    padding-bottom: 11px;
    padding-left: 48px;
    padding-right: 48px;
    line-height: normal;
    float: left;
    cursor: pointer;
    margin-right: 6px;
    transition: 0.3s all ease-in-out;
    border-radius: 0;
    font-size: 14px;
    font-size: 1.4rem;
    transform: skew(-20deg);
    -webkit-transform: skew(-20deg);
    -moz-transform: skew(-20deg);
    -o-transform: skew(-20deg);
"
                                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                                        class="action primary tocart"
                                        id="product-addtocart-button">
                                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                                </button>
                                <?php echo $block->getChildHtml('', true) ?>
                            </div>
                        </div>

                        <?php
                        if($_product->getTypeId() != 'virtual' && $_product->getTypeId() != 'downloadable') {
                            /* integrate calculate shipping */
                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $helper = $objectManager->get('\Netbaseteam\Calculatorshipping\Helper\Data');
                            echo $helper->showShippingEstimate();
                        }
                        ?>
                    </div>
                <?php endif; ?>
            <?php }
            else {
?>
                <?php $buttonTitle = __('Add to Cart'); ?>
                <?php if ($_product->isSaleable()): ?>
                    <div class="box-tocart">
                        <div class="fieldset" style="
    display: none;
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,0.7);
    z-index: 9999;
    padding-top: 42%;
    padding-right: 40px;
    padding-left: 40px;
">
                            <span id="close-quote-wrap" style="
    position: absolute;
    top: 10px;
    right: 20px;
    cursor: pointer;
    color: white;
    font-size: 24px;
">X</span>
                            <?php if ($block->shouldRenderQuantity()): ?>
                                <div class="field qty">
                                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                                            echo __('Qty') ?></span></label>
                                    <div class="control">
                                        <button type="button" class="subtract">-</button>
                                        <input type="number"
                                               name="qty"
                                               id="qty"
                                               maxlength="12"
                                               value="<?php /* @escapeNotVerified */
                                               echo $block->getProductDefaultQty() * 1 ?>"
                                               title="<?php /* @escapeNotVerified */
                                               echo __('Qty') ?>" class="input-text qty"
                                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                        />

                                        <button type="button" class="add">+</button>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <div class="actions">
                                <button type="submit"
                                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                                        class="action primary tocart"
                                        style="
    background-color: #d1242e;
    border: 1px solid #d1242e;
    color: #ffffff;
    text-transform: uppercase;
    padding-top: 10px;
    padding-bottom: 11px;
    padding-left: 48px;
    padding-right: 48px;
    line-height: normal;
    float: left;
    cursor: pointer;
    margin-right: 6px;
    transition: 0.3s all ease-in-out;
    border-radius: 0;
    font-size: 14px;
    font-size: 1.4rem;
    transform: skew(-20deg);
    -webkit-transform: skew(-20deg);
    -moz-transform: skew(-20deg);
    -o-transform: skew(-20deg);
"
                                        id="product-addtocart-button">
                                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                                </button>
                                <?php echo $block->getChildHtml('', true) ?>
                            </div>
                        </div>

                        <button type="button"
                                title="<?php /* @escapeNotVerified */ echo __("Request a Quote") ?>"
                                style="
    background-color: #d1242e;
    border: 1px solid #d1242e;
    color: #ffffff;
    text-transform: uppercase;
    padding-top: 10px;
    padding-bottom: 11px;
    padding-left: 48px;
    padding-right: 48px;
    line-height: normal;
    float: left;
    cursor: pointer;
    margin-right: 6px;
    transition: 0.3s all ease-in-out;
    border-radius: 0;
    font-size: 14px;
    font-size: 1.4rem;
    transform: skew(-20deg);
    -webkit-transform: skew(-20deg);
    -moz-transform: skew(-20deg);
    -o-transform: skew(-20deg);
"
                                class="request-a-quote action primary tocart"
                                id="product-addtocart-button">
                            <span><?php /* @escapeNotVerified */ echo __("Request a Quote") ?></span>
                        </button>

                        <?php
                        if($_product->getTypeId() != 'virtual' && $_product->getTypeId() != 'downloadable') {
                            /* integrate calculate shipping */
                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $helper = $objectManager->get('\Netbaseteam\Calculatorshipping\Helper\Data');
                            echo $helper->showShippingEstimate();
                        }
                        ?>
                    </div>
                <?php endif; ?>
            <?php } ?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $(document.body).on('click', '.request-a-quote', function () {
            $('.box-tocart > .fieldset') .toggle();
        });

        $(document.body).on('click', '#close-quote-wrap', function () {
            $('.box-tocart > .fieldset') .toggle();
        });
    });
</script>
