<?php
/**
 * Nav view template
 *
 * @var $block \Continental\Nav\Block\SideProducts
 */
?>
<div class="category-nav">
	<?php echo $this->SideSubMenu(); ?>
</div>

<?php // background image
//echo "Testing background: [" . $this->categoryBackgroundImage() . "]";
?>
<script>
	require(['jquery'], function($) {

		// This adds a wrapping div around main content called category-bg. It then finds the h1 parent div and puts drops the h1 inside the ul. Gives the category bg a style attribute and gets the category image from the cms.

	$( ".page-with-filter #maincontent" ).wrap( "<div class='category-bg'></div>" );
	$(".category-bg").find('.page-title-wrapper').prependTo('.category-nav ul');
	$(".category-bg").css({"background-image":"url('<?php echo $this->categoryBackgroundImage(); ?>')"});
	});
</script>
