<div style="text-align:center;">
<canvas id="canvas" width="600" height="500"></canvas>
</div>
<script>
require(["jquery"], function($){
var canvas = document.getElementById('canvas');
var ctx = canvas.getContext('2d');
var rect = {};
var drag = false;
var imageObj = null;

function init() {
    imageObj = new Image();
    imageObj.onload = function () { ctx.drawImage(imageObj, 0, 0); };
    imageObj.src = "http://www.continentalsports.co.uk/img/spares/13-large_spares.jpg";
    canvas.addEventListener('mousedown', mouseDown, false);
    canvas.addEventListener('mouseup', mouseUp, false);
    canvas.addEventListener('mousemove', mouseMove, false);
}

function mouseDown(e) {
    rect.startX = e.pageX - this.offsetLeft;
    rect.startY = e.pageY - this.offsetTop;
    drag = true;
}

function mouseUp() { drag = false; }

function mouseMove(e) {
    if (drag) {
        ctx.clearRect(0, 0, 500, 500);
        ctx.drawImage(imageObj, 0, 0);
        rect.w = (e.pageX - this.offsetLeft) - rect.startX;
        rect.h = (e.pageY - this.offsetTop) - rect.startY;
        ctx.strokeStyle = '#373330';
        ctx.strokeRect(rect.startX, rect.startY, rect.w, rect.h);
	ctx.fillStyle = 'rgba(225,225,225,0.2';
//	ctx.fillStyle = 'black, 0.5';
//	ctx.globalAlpha = 0.2;
	ctx.fillRect(rect.startX, rect.startY, rect.w, rect.h);
	// save co-ordinates
        $("input[name='co_ords1']").val(rect.startX + "," + rect.startY);
        $("input[name='co_ords2']").val(rect.w + "," + rect.h);
    }
}
//
init();
});
</script>
