<h1>Testing</h1>
<table class="admin__dynamic-rows data-grid" data-role="grid">
    <thead>
    <tr>
    <th class="data-grid-th">Image</th>
    <th class="data-grid-th">Name</th>
    <th class="data-grid-th">Code</th>
    <th class="data-grid-th">Price</th>
    <th class="data-grid-th">Quantity</th>
    <th class="data-grid-th">Weight</th>
    <th class="data-grid-th">Status</th>
    <th class="data-grid-th">Attributes</th>
    <th class="data-grid-th">Actions</th>
    </tr>
    </thead>
    <tbody>
    <tr><td></td></tr>
    </tbody>
</table>
