<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var \Magento\Framework\Pricing\Render\Amount $block */ ?>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$registry = $objectManager->get('\Magento\Framework\Registry');
$currentProduct = $registry->registry('current_product');

$_children = $currentProduct->getTypeInstance()->getUsedProducts($currentProduct);
$data = $currentProduct->getTypeInstance()->getConfigurableOptions($currentProduct);
foreach ($_children as $child) {
if($child->getTierPrice()) { ?>

    <table class="tier-table" style="display: none;" data-sku="<?php echo $child->getSku() ?>">
        <tr>
            <th>Qty</th>
            <th>Discount</th>
            <th>Base price</th>
        </tr>
        <?php foreach ($child->getTierPrice() as $tierPrice): ?>
            <tr>
                <td>x<?php echo round($tierPrice['price_qty']) ?></td>
                <td>
                    <?php if ($tierPrice['percent'] != -1): ?>
                        <?php echo $tierPrice['percent'] ?>
                    <?php else: ?>
                        <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($child->getFinalPrice() - $tierPrice['price'],2),true,false); ?>
                    <?php endif; ?>
                </td>
                <td><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($child->getFinalPrice(),2),true,false) ?></td>
            </tr>
        <?php endforeach; ?>
    </table>

    <?php
}
} ?>
<span class="con-price-from">Price from:</span>
<span class="price-container <?php /* @escapeNotVerified */
echo $block->getAdjustmentCssClasses() ?>"
    <?php echo $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>

    <?php if ($block->getDisplayLabel()): ?>

        <span class="price-label"><?php /* @escapeNotVerified */
            echo $block->getDisplayLabel(); ?></span>
    <?php endif; ?>

    <span <?php if ($block->getPriceId()): ?> id="<?php /* @escapeNotVerified */
        echo $block->getPriceId() ?>"<?php endif; ?>
        <?php echo ($block->getPriceDisplayLabel()) ? 'data-label="' . $block->getPriceDisplayLabel() . $block->getPriceDisplayInclExclTaxes() . '"' : '' ?>
            data-price-amount="<?php /* @escapeNotVerified */
            echo $block->getDisplayValue(); ?>"
            data-price-type="<?php /* @escapeNotVerified */
            echo $block->getPriceType(); ?>"
            class="price-wrapper <?php /* @escapeNotVerified */
            echo $block->getPriceWrapperCss(); ?>"
        <?php echo $block->getSchema() ? ' itemprop="price"' : '' ?>>

        

        <?php /* @escapeNotVerified */
        echo $block->formatCurrency($block->getDisplayValue(), (bool)$block->getIncludeContainer()) ?>
    </span>
    <?php if ($block->hasAdjustmentsHtml()): ?>
        <?php echo $block->getAdjustmentsHtml() ?>
    <?php endif; ?>
    <?php if ($block->getSchema()): ?>
        <meta itemprop="priceCurrency" content="<?php /* @escapeNotVerified */
        echo $block->getDisplayCurrencyCode() ?>"/>
    <?php endif; ?>
</span>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($) {
        $('.super-attribute-select').on('change', function () {
            console.log($('.sku div[itemprop="sku"]').text());
            $('.tier-table[data-sku="' + $('.sku div[itemprop="sku"]').text()  + '"]').show();
        });
    });
</script>