<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . __('* Required Fields') . '"';
}
?>
<div class="product-options-wrapper" id="product-options-wrapper"<?php /* @escapeNotVerified */
echo $required; ?>>
    <div class="fieldset" tabindex="0">
        <?php echo $block->getChildHtml('', true); ?>
    </div>
</div>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$registry = $objectManager->get('\Magento\Framework\Registry');
$currentProduct = $registry->registry('current_product');
if ($currentProduct) {
    $_children = $currentProduct->getTypeInstance()->getUsedProducts($currentProduct);
    $data = $currentProduct->getTypeInstance()->getConfigurableOptions($currentProduct);
    if (count($_children)) {
        foreach ($_children as $child) {
            if ($child->getTierPrice()) {
                ?>

                <table class="tier-table" style="display: none;" data-sku="<?php echo $child->getSku() ?>">
                    <tr>
                        <th>Qty</th>
                        <th>Discount</th>
                        <th>Base price</th>
                    </tr>
                    <?php foreach ($child->getTierPrice() as $tierPrice): ?>
                        <tr>
                            <td>x<?php echo round($tierPrice['price_qty']) ?></td>
                            <td>
                                <?php
                                echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($child->getFinalPrice() - $tierPrice['price'], 2), true, false); ?>
                            </td>
                            <td><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($child->getFinalPrice(),
                                    2), true, false) ?></td>
                        </tr>
                    <?php endforeach;

                    ?>
                </table>

                <?php
            }
        }
    }
}
?>
<script>
    require(['jquery'], function ($) {
        $('body').on('DOMNodeInserted', function (e) {
            if ($(e.target).hasClass('swatch-attribute')) {
                $('.color .swatch-option.image').each(function () {
                    var $this = $(this);
                    $this.css('background-image', $this.css('background-image').replace(/swatch_image\/30x20/, 'swatch_thumb/110x90'));
                });
            }
        });
    });
</script>