<script type="text/javascript">
    require(
        ['jquery',
            'mage/url'
        ],
        function ($, url) {
            $(document).ready(function () {
                $(function () {
                    $.ajax({
                        url: '<?php echo $block->getUrl('documents/index/preselect') ?>',
                        type: 'POST',
                        dataType: 'json',
                        complete: function (data) {
                            console.log(data);
                        }
                    });
                });
            });
        });
</script>
