<html>
<head>
<title>{%title%}</title>
<link  rel="stylesheet" type="text/css"  media="all" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
<link  href="//fonts.googleapis.com/css?family=Montserrat:700|Roboto:300,400,700" rel="stylesheet" type="text/css" href="" />
<link  rel="stylesheet" type="text/css"  media="all" href="http://continental.attercopia.co.uk/static/frontend/Attercopia/continental/en_GB/css/styles.css" />
<style>
 .pdf-main { padding:40px; padding-top:0 }
 table { width: 100% } 
 td { padding:6px; }
 .col3 { text-align:center }
 img { max-height: 450px; }
</style>
</head>
<body>
<div class="pdf pdf-wrapper">
		<div class="pdf-main">
			<div class="pdf-container">
				<h1>{%title%}</h1>
				<p class="pdf-sku">{%sku-master%}</p>
				
				<div class="pdf-product-img">
					<img src="{%mainimage%}" alt="Product">
				</div>

				<div class="pdf-description">
					<h2>Details</h2>
					<p>	
					{%description%}
					</p>
				</div>
				<div class="pdf-table">
					<table>
						<thead>
							<tr style="background-color:#F5F5F5">
								<th>SKU</th>
								<th>Options</th>
								<th>Available Colours</th>
							</tr>
						</thead>
						<tbody>
					<!-- [CONFIGURATION_START] -->
							<tr>
								<td>{%sku%}</td>	
								<td>{%options%}</td>	
								<td class="col3">{%colour%}</td>	
							</tr>

							<!-- [CONFIGURATION_END] -->
						</tbody>
					</table>
				</div>
				<!-- footer removed from this template -->
			</div>
		</div>

</div>
</body>
</html>
