<html>
<head>
<title>{%title%}</title>
<link  rel="stylesheet" type="text/css"  media="all" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
<link  rel="stylesheet" type="text/css"  media="all" href="http://continental.attercopia.co.uk/static/version1502807272/frontend/Attercopia/continental/en_GB/mage/calendar.css" />
<link  rel="stylesheet" type="text/css"  media="all" href="http://continental.attercopia.co.uk/static/version1502807272/frontend/Attercopia/continental/en_GB/css/styles.css" />
<link  rel="stylesheet" type="text/css"  media="all" href="http://continental.attercopia.co.uk/static/version1502807272/frontend/Attercopia/continental/en_GB/Amasty_HidePrice/js/fancybox/jquery.fancybox.css" />
<link  rel="stylesheet" type="text/css"  media="print" href="http://continental.attercopia.co.uk/static/version1502807272/frontend/Attercopia/continental/en_GB/css/print.css" />
<link  href="//fonts.googleapis.com/css?family=Montserrat:700|Roboto:300,400,700" rel="stylesheet" type="text/css" href="" />
<link  rel="icon" type="image/x-icon" href="http://continental.attercopia.co.uk/media/favicon/stores/1/favicon-16x16_1.png" />
<link  rel="shortcut icon" type="image/x-icon" href="http://continental.attercopia.co.uk/media/favicon/stores/1/favicon-16x16_1.png" />
</head>
<body>
<div class="pdf pdf-wrapper">
<!--
		<div class="pdf-header" style="background-color:#333!important">
			<div class="pdf-container">
				<img src="http://continental.attercopia.co.uk/static/version1502457461/frontend/Attercopia/continental/en_GB/images/footer-logo.png" alt="PDF Logo">
			</div>
		</div>
-->
		<div class="pdf-main">
			<div class="pdf-container">
				<h1>{%title%}</h1>
				<p class="pdf-sku">{%sku-master%}</p>
				
				<div class="pdf-product-img">
					<img src="{%mainimage%}" alt="Product">
				</div>

				<div class="pdf-description">
					<h2>Details</h2>
					<p>	
					{%description%}
					</p>
				</div>
				<div class="pdf-table">
					<table>
						<thead>
							<tr style="background-color:#F5F5F5">
								<th>SKU</th>
								<th>Options</th>
								<th>Available Colours</th>
							</tr>
						</thead>
						<tbody>
					<!-- [CONFIGURATION_START] -->
							<tr>
								<td>{%sku%}</td>	
								<td>{%options%}</td>	
								<td>{%colour%}</td>	
							</tr>

							<!-- [CONFIGURATION_END] -->
						</tbody>
					</table>
				</div>
				<!-- footer removed from this template -->
			</div>
		</div>

</div>
</body>
</html>
