<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
// Load contiproducts class
$_productCollection = $block->getLoadedProductCollection();

$_helper = $this->helper('Magento\Catalog\Helper\Output');

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>

        <style>
            .products.list.items {
                display: inline-block;
            }

            .column.main {
                float: left!important;
                width: 100%!important;
            }
        </style>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">

                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <?php if ($_product->getShortDescription()):?>
                            <div class="product-information">
                        <?php else: ?>
                            <div class="product-information no-description">
                        <?php endif; ?>
                            <div class="product-item-wrapper">
                                <strong class="product name product-item-name">
                                <a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </strong>
                                </div>
                             <?php if ($_product->getShortDescription()):?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                </div>
                            <?php endif; ?>
<?php
// Load contiproducts class
$contiproducts = $this->getLayout()->createBlock('\Continental\Products\Block\Details');
?>

                        </div>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <!-- <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary btn btn-secondary">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?> -->

                                </div>

                                <a class="btn btn-secondary" title="View Item"
                                   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                    <span>View Item</span>
                                </a>
                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <style>

        @media screen and (min-width: 1024px) {
            .filter-options {
                width: 100%;
                display: inline-block;
                padding-top: 15px !important;
                padding-bottom: 15px !important;
                border-bottom: 1px solid #e4e4e4;
                border-top: 1px solid #e4e4e4;
                margin-top: 30px !important;
            }

            .filter-options-title {
                float: left;
                margin-right: 30px !important;
                margin-bottom: 0 !important;
                color: #a3a3a3 !important;
                cursor: pointer;
                padding-top: 2px;
                font-weight: 500 !important;
                position: relative;
                padding-right: 20px !important;
            }

            .filter-options-title:before {
                font-family: FontAwesome;
                content: "\f0d7";
                position: absolute;
                top: 2px;
                right: 0;
            }

            .block-subtitle.filter-subtitle {
                color: #d1242e;
                margin-bottom: 0 !important;
                margin-right: 30px !important;
                float: left !important;
            }

            .filter-options-content {
                display: none;
                width: 200px;
                position: absolute;
                margin-top: 0px !important;
                background: white;
                z-index: 999999;
                box-shadow: 0 2px 10px #3c3c3c;
                padding: 10px;
            }

            .filter-options-title:hover > .filter-options-content {
                display: block;
            }

            .filter-options-content:hover {
                display: block;
            }
        }

    </style>
    <?php /* -- sort images and height -- */ ?>
<script type="text/javascript">
     require(["jquery"], function ($) {
        $(document).ready(function() {
            
        equalHeight(".product-item-name");
        equalHeight(".list.items .product-item-description");
        function equalHeight(el) {
        var maxHeight = 0;
        $(el).each(function() {
            x = $(this).height();
            console.log(el + " = " + x);
            if (x > maxHeight) {
                maxHeight = x;
            }
        });
        $(el).height(maxHeight);
        }
         jQuery(".product-item-info img").css({"width":"inherit","display":"block","margin":"0 auto"});
        });
       
    });
</script>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
