<?php
/** @var \Mirasvit\Kb\Block\Article\View $block */
//@codingStandardsIgnoreFile
$article = $block->getArticle();
$tags = $block->getTags();
$helper = $this->helper('\Mirasvit\Kb\Helper\Document');

?>

<?= $block->getChildHtml('kb.search.form') ?>

<?= $block->getKbPageTitle() ?>

<div class="kb-article__metadata">
    <div class="author">
        <?php if ($block->isShowAuthor()): ?>
            <?= $article->getUser()->getName(); ?>
        <?php endif; ?>
        <?php if ($block->isShowDate()): ?>
            <?php if ($block->isShowAuthor()): ?>
                <?= __(' posted this at '); ?>
            <?php endif; ?>
            <?= $block->formatDate($article->getCreatedAt(), \IntlDateFormatter::MEDIUM); ?>
        <?php endif; ?>
    </div>

    <?php if ($article->getRating() && $block->isRatingEnabled()): ?>
        <div class="rating">
            <i class="fa fa-thumbs-o-up"></i><?= $article->getPositiveVoteNum() ?>
        </div>
    <?php endif ?>
</div>

<div class="kb-article__body cms-content">
    <?= $article->getTextHtml() ?>
</div>
<!-- show available downloads -->
<?php // get downloads ?>
<div class="doc-section">
    <div class="doc-section-head">
        <div>
            <span>Download</span>
        </div>
        <div>
            <span>Description</span>
        </div>
        <div>
            <span>Date Uploaded</span>
        </div>
    </div>
    <?php
    $documentList = $helper->getAllDocuments($article->getDocuments());
    if (count($documentList) > 0) {
        foreach ($documentList as $index => $row):
            ?>
            <div class="doc-section-row">
                <div>
                    <a href="<?= $helper->getDocumentUrl($row['documentfile'])?>"><i class="fa fa-file-pdf-o" aria-hidden="true"></i><?=$row['title']?></a><span class="size"><small>
                            (<?= $helper->getFileSize($row['documentfile'])?> kb)
                        </small></span>
                </div>
                <div>
                    <p><?=$row['description']?></p>
                </div>
                <div>
                    <span class="date"><?=date("d.m.Y", strtotime($row['created_at']))?></span>
                </div>
            </div>
        <?php endforeach;
    }
    ?>
</div>
<div class="spacer">&nbsp;</div>
<!-- end of downloads section -->

<div class="kb-article__body-info-left">
    <div class="kb-article__categories">
        <?= __('Categories:') ?>
        <?php foreach ($block->getCategories() as $category): ?>
            <span><a href='<?= $category->getUrl() ?>'><?= $category->getName() ?></a></span>
        <?php endforeach ?>
    </div>


    <div class="kb-article__tags">
        <?php if ($tags->count()): ?>
            <?= __('Tags:') ?>
            <?php foreach ($tags as $tag): ?>
                <span><a href='<?= $tag->getUrl() ?>'><?= $tag->getName() ?></a>&nbsp;</span>
            <?php endforeach ?>
        <?php endif ?>
    </div>
</div>
<div class="kb-article__body-info-right">
    <?php if ($block->isRatingEnabled()): ?>
        <div class="kb-article__helpful">
            <?php if (!$block->getVoteResult()): ?>
                <div class="metadata">
                    <strong><?= __('Was this article helpful?'); ?></strong>
                    <span
                        class="count"><?= __('%1 out %2 found this helpful', $article->getPositiveVoteNum(), $article->getVotesNum()); ?></span>
                </div>
                <a href="<?= $block->getVoteUrl(5) ?>"><i class="fa fa-thumbs-o-up"></i></a>
                <a href="<?= $block->getVoteUrl(1) ?>"><i class="fa fa-thumbs-o-down"></i></a>
            <?php else: ?>
                <?php if ($block->getVoteResult() == 5): ?>
                    <div class="metadata">
                    <span class="count">
                        <?php if ($article->getPositiveVoteNum() > 1): ?>
                            <?= __('You and %1 people found this helpful.', $article->getPositiveVoteNum()) ?>
                        <?php else: ?>
                            <?= __('You found this helpful.') ?>
                        <?php endif ?>
                    </span>
                    </div>
                <?php endif ?>
            <?php endif ?>
        </div>
    <?php endif ?>
</div>
<div class="clearfix"></div>
<!-- clearing comment providers -->

