<?php
//@codingStandardsIgnoreFile

/** @var \Mirasvit\Blog\Block\Post\PostList $block */
$collection = $block->getPostCollection();
?>

<?php if ($collection->count()): ?>
    <div class="blog__post-list-wrapper">
        <ol class="blog__post-list">
            <?php /** @var \Mirasvit\Blog\Model\Post $post */ ?>
            <?php foreach ($collection as $post): ?>
                <li class="blog__post-item">
                    <div class="news-cat-left">
                        <?php if ($post->getFeaturedImageUrl()): ?>
                            <a href="<?= $post->getUrl() ?>">
                                <img src="<?= $post->getFeaturedImageUrl() ?>" alt="<?= $post->getName() ?>"/>
                            </a>
                        <?php endif ?>
                    </div>
                    <div class="news-cat-right">
                        <header class="blog__post-header">
                            <h2 class="blog__post-title" itemprop="headline">
                                <a href="<?= $post->getUrl() ?>" rel="bookmark"><?= $post->getName() ?></a>
                            </h2>

                            <?= $block->getPostMetaHeader($post)->toHtml() ?>
                        </header>

                        <div class="blog__post-excerpt" itemprop="text">                        

                            <?= $post->getShortContent() ?>

                            <a class="read-more btn btn-primary" href="<?= $post->getUrl() ?>"><span><?= __('Read more') ?></span></a>
                        </div>
                    </div>                   

                    <!-- <?= $block->getPostMetaFooter($post)->toHtml() ?> -->
                </li>
            <?php endforeach ?>
        </ol>

       <?php echo $block->getToolbarHtml() ?> 
    </div>
<?php else: ?>
    <div class="message notice">
        <div><?= __('There are no posts available for this category.') ?></div>
    </div>
<?php endif ?>
