<?php
//@codingStandardsIgnoreFile
/** @var \Mirasvit\Blog\Block\Post\View $block */

//$core = $this->getLayout()->createBlock('\Continental\General\Block\Core');
$core = $this->helper('Continental\General\Helper\Core');
echo $core->strip_additional_para('<p>This is a test</p><p>This shouldn\'t appear</p>');

$post = $block->getPost();
?>

<div class="blog__post-view">

    <?= $this->getPostMetaHeader()->toHtml() ?>

    <?php if ($post->getFeaturedImageUrl()): ?>
        <img src="<?= $post->getFeaturedImageUrl() ?>"  alt="<?= $post->getName() ?>" class="blog__post-featured-image"/>
    <?php endif ?>

    <?= $block->getPostContent() ?>


    <?= $this->getChildHtml('blog.post.related.posts') ?>

    <?= $this->getChildHtml('blog.post.related.products') ?>

    <?= $this->getChildHtml('blog.post.comments') ?>
</div>
