<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="social-icons">
	<a href="" title="Linked In" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
	<a href="" title="Twitter" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
	<a href="" title="Facebook" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
</div>