<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>

<div class="spares-media">

	<div class="image-map">
<!-- get spares image -->
		<img src="<?php echo $this->getViewFileUrl('images/trampoline.jpg'); ?>" alt="test" />

		<a class="map-section" style="width:100px;height:50px;top:55%;left:33%;" href="#"></a>

	</div>
</div>
