<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/

$_product = $block->getProduct();


?>
<div class="page-title-wrapper">
    <h1 class="page-title"><span class="base" data-ui-id="page-title-wrapper"><?=$_product->getName();?></span>    </h1>
</div>

<div class="product attribute sku">
    <strong class="type"></strong>    <div class="value"><?=$_product->getSku();?></div>
</div>


<div class="product-buttons">
  <a class="btn-pdf" href="/pdf/?id=<?=$_product->getId(); ?>"><span>Brochure</span></a>
  <button class="btn-spares"><span style="visibility: hidden;"></span>Back to product</button>
</div>
<?php
$collection = $block->getRelatedProducts();
?>
<ol class="products list items product-items"><?php foreach ($collection as $product): ?><li class="item product product-item">
                    <div class="product-item-info">
                        <a href="<?= $block->getProductUrl($product) ?>" class="product photo product-item-photo">
                            <?= $block->getImage($product, 'related_products_list')->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <a class="product-item-link" title="<?= $block->escapeHtml($product->getName()) ?>"
                                   href="<?= $block->getProductUrl($product) ?>">
                                    <?= $block->escapeHtml($product->getName()) ?>
                                </a>
                            </strong>
                            <?= $block->getProductPrice($product) ?>
                        </div>
                    </div>
                    </li><?php endforeach ?></ol>
        </div>
    </ol>

