<?php
/**
 * Nav view template
 *
 * @var $block \Continental\Nav\Block\SideProducts
 */
?>
<div class="category-nav">
    <?php echo $this->SideSubMenu(); ?>

    <div class="category-holder">
        <?php if ($title = $block->getName()): ?>
            <?php echo '<h2 class="cat-title">'.$title.'</h2>'; ?>
        <?php endif; ?>
        <?php if ($description = $block->getDescription()): ?>
            <?php echo '<div class="cat-desc">'.$description.'</div>'; ?>
        <?php endif; ?>
    </div>
</div>

<?php // background image
//echo "Testing background: [" . $this->categoryBackgroundImage() . "]";
?>
<script>
    require(['jquery'], function ($) {

        // This adds a wrapping div around main content called category-bg. It then finds the h1 parent div and puts drops the h1 inside the ul. Gives the category bg a style attribute and gets the category image from the cms.

        $("#maincontent").wrap("<div class='category-bg'></div>");
        $(".category-bg").find('.page-title-wrapper').prependTo('.category-nav ul');

        <?php
        if ($this->categoryBackgroundImage()):
        ?>

        $(".category-bg").css({"background-image": "url('<?php echo $this->categoryBackgroundImage(); ?>')"});

        <?php
        endif;
        ?>

    });
</script>
