<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Basket'); ?>

<?php if ($_product->getTypeId() == 'simple' || $_product->getTypeId() == 'virtual'): ?>
    <div class="price-box price-final_price" data-role="priceBox" data-product-id="<?php echo $_product->getId() ?>">
    <span class="price-container">
    <span id="product-price-<?php echo $_product->getId() ?>"
          data-price-amount="<?php echo $_product->getFinalPrice() ?>" data-price-type="finalPrice"
          class="price-wrapper " itemprop="price">
        <span class="price"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_product->getFinalPrice(), true, false); ?></span>
    </span>
    </span>
    </div>
<?php endif; ?>

<?php

if ($_product->isSaleable()): ?>
    <?php ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                            echo __('Qty') ?></span></label>
                    <div class="control">
                        <button type="button" class="subtract">-</button>
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?php /* @escapeNotVerified */
                               echo $block->getProductDefaultQty() * 1 ?>"
                               title="<?php /* @escapeNotVerified */
                               echo __('Qty') ?>" class="input-text qty"
                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />

                        <button type="button" class="add">+</button>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */
                        echo $buttonTitle ?>"
                        class="btn btn-primary"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */
                        echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>

        <?php
        if($_product->getTypeId() != 'virtual' && $_product->getTypeId() != 'downloadable') {
            /* integrate calculate shipping */
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $helper = $objectManager->get('\Netbaseteam\Calculatorshipping\Helper\Data');
            echo $helper->showShippingEstimate();
        }
        ?>
    </div>
    <?php ?>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }

</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }

    </script>
<?php endif; ?>
