<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/

$_product = $block->getProduct();

?>
<div class="product-buttons" style="margin-top: -10px; -webkit-transform: skew(-20deg);">
    <a class="btn-pdf" href="/pdf/?id=<?=$_product->getId(); ?>"><span style="transform: skew(20deg);">Brochure</span></a>
    <?php 
	// hide this button if there are no spares available
        $related    = $this->getLayout()->createBlock('\Continental\Spares\Block\RelatedProducts');
	$collection = $related->getRelatedProducts();
    $showSpares = (is_array($collection) && !empty($collection)) ? true : false;
	if ($showSpares): ?>
	<button class="btn-spares"><span></span>Spares</button>
	<?php endif; ?>
</div>


